version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - web_data:/app  
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    command: bash -c "flask run & celery --concurrency=1 -A app.celery worker --loglevel=info"

volumes:
  rabbitmq_data:
  web_data:
